---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(viridis)
library(ggpubr)
library(here)
```

```{r}
df_flat <- read.csv(here("data_output/eval/df_eval_contacts_m_flat.csv"))
df_flat <- df_flat[!duplicated(df_flat[,c("simulation", "polymod")]),]
```

```{r}
df_m_sim <- read.csv(here("data_output/eval/df_eval_contacts_m_sim.csv"))
names(df_m_sim)[names(df_m_sim) == "X"] <- "i"
df_m_sim <- tidyr::pivot_longer(
  df_m_sim, 
  cols=tidyr::starts_with("X"), 
  names_to = "j", 
  values_to = "Contacts"
  )
df_m_sim$j <- gsub("X", "", df_m_sim$j)
df_m_sim$j <- as.numeric(df_m_sim$j)
df_m_sim$i <- df_m_sim$i * 5
df_m_sim$j <- df_m_sim$j * 5
```

```{r}
df_m_emp <- read.csv(here("data_output/eval/df_eval_contacts_m_emp.csv"))
names(df_m_emp)[names(df_m_emp) == "X"] <- "i"
df_m_emp <- tidyr::pivot_longer(df_m_emp, cols=tidyr::starts_with("X"), names_to = "j", values_to = "Contacts")
df_m_emp$j <- gsub("X", "", df_m_emp$j)
df_m_emp$j <- as.numeric(df_m_emp$j)
df_m_emp$i <- df_m_emp$i * 5
df_m_emp$j <- df_m_emp$j * 5
```

```{r}
# chi-square test
matrix_emp <- read.csv(here("data_output/eval/df_eval_contacts_m_emp.csv"))[,2:17]
matrix_sim <- read.csv(here("data_output/eval/df_eval_contacts_m_sim.csv"))[,2:17]

chi_square <- sum((matrix_sim - matrix_emp)^2 / matrix_emp)

degrees_of_freedom <- (nrow(matrix_sim) - 1) * (ncol(matrix_sim) - 1)

p <- pchisq(chi_square, 225, lower.tail = F)

print(p)
```


```{r}
g_m_sim <- (
  ggplot(data=df_m_sim, mapping=aes(x=i, y=j, fill=Contacts))
  + geom_tile()
  + scale_fill_viridis(option="inferno", discrete=FALSE, limits=c(0,4.5), )
  + theme_bw()
  + theme(plot.title = element_text(hjust = 0.5))
  + xlab("Age group i")
  + ylab("Age group j")
  + ggtitle("Simulated age contact matrix")
  + xlim(-5,75)
  + ylim(-5,75)
  + theme(plot.margin = unit(c(1,1,1,1), 'lines'))
  + theme(axis.text = element_text(size = 8), axis.title = element_text(size = 9))
)
g_m_sim
```

```{r}
g_m_emp <- (
  ggplot(data=df_m_emp, mapping=aes(x=i, y=j, fill=Contacts))
  + geom_tile()
  + scale_fill_viridis(option="inferno", discrete=FALSE, limits=c(0,4.5))
  + theme_bw()
  + theme(plot.title = element_text(hjust = 0.5))
  + theme(axis.text = element_text(size = 8), axis.title = element_text(size = 9))
  + xlab("Age group i")
  + ylab("Age group j")
  + ggtitle("Empirical age contact matrix")
  + theme(plot.margin = unit(c(1,1,1,1), 'lines'))
  + xlim(-5,75)
  + ylim(-5,75)
)
g_m_emp
```

```{r}
g_m_corr <- (
  ggplot(data=df_flat, mapping=aes(y=simulation, x=polymod))
  + geom_point(size=0.5)
  + theme_bw()
  + geom_abline(intercept=0, slope=1, linetype="dashed")
  + geom_smooth(method=lm, size=0.5, alpha=0.1, se=F)
  + theme(aspect.ratio=1)
  + theme(plot.title = element_text(hjust = 0.5))
  + ylab("Simulated number of contacts")
  + xlab("Empirical number of contacts")
  + ggtitle("Relation between contact frequencies")
  + theme(plot.margin = unit(c(1,1,1,1), 'lines'))
  + theme(axis.text = element_text(size = 8), axis.title = element_text(size = 9))
  + xlim(0,5)
  + ylim(0,5)
  
)
g_m_corr
```

```{r}
cor.test(df_flat$simulation, df_flat$polymod)
```

```{r}
ggarrange(
  g_m_emp,
  g_m_sim,
  g_m_corr,
  labels = c("A", "B", "C"),
  ncol = 3
  )
ggsave(here::here("img/fig_eval_contacts.pdf"), width = 17, height = 5, dpi = 300)
ggsave(here::here("img/fig_eval_contacts.png"), width = 17, height = 5, dpi = 300)
```
