---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

here()
rm(list = ls())
gc()

library(ggplot2)
library(pscl)
library(MASS)
library(boot)
library(sjPlot)
library(lme4)
library(glmmTMB)
library(jtools)
library(here)
library(interactions)
library(ggpubr)
library(vroom)

source(here("src/research/def_data_prep.R"))
```

```{r}
get_replications <- function(df, f, col){
  
  vec_results <- vector(length=nrow(df))
  
  for (i in 1:nrow(df)){
    df_sample <- df[sample(nrow(df), size=i),]
    result <- f(df_sample[,col])
    vec_results[[i]] <- result
  }
  
  df_results <- data.frame("n"=1:nrow(df), "estimate"=vec_results)
  
  return(df_results)
}
```


### Eval reps of calibration model

```{r}
df <- do.call(rbind, list(
  vroom::vroom(here("data_output/reg/df_agents_reg_PART_0.csv")),
  vroom::vroom(here("data_output/reg/df_agents_reg_PART_1.csv")),
  vroom::vroom(here("data_output/reg/df_agents_reg_PART_2.csv")),
  vroom::vroom(here("data_output/reg/df_agents_reg_PART_3.csv"))
))
```


```{r}
df$ever_infected <- ifelse(df$ever_infected=="True", 1, 0)
df$ever_infected_with_symptoms <- ifelse(df$ever_infected_with_symptoms=="True", 1, 0)


# counts per replication 
df_agg <- aggregate(
   x=list(
     "ever_infected"=df$ever_infected,
     "ever_infected_with_symptoms"=df$ever_infected_with_symptoms
     ),
   by=list(
     "replication"=df$replication
     
     ),
   FUN=sum
 )
```

```{r}
df_mean <- get_replications(df_agg, mean, "ever_infected")
(
  ggplot(data=df_mean, mapping=aes(x=n, y=estimate))
  + geom_point()
  + geom_line()
  + ylim(0, NaN)
  + xlab("Number of replications")
  + ylab("Average number of infected agents")
  + title("Evaluation of the number of replications in the calibration model")
)
```
### Eval reps of regression model

```{r}
# load data

df_agents_exp_raw <- do.call(rbind, list(
  vroom::vroom(here("data_output/reg/df_agents_reg_PART_0.csv")),
  vroom::vroom(here("data_output/reg/df_agents_reg_PART_1.csv")),
  vroom::vroom(here("data_output/reg/df_agents_reg_PART_2.csv")),
  vroom::vroom(here("data_output/reg/df_agents_reg_PART_3.csv"))
))

#df_agents_exp_raw <- vroom::vroom(here("data_output/reg/df_agents_baseline_age-specific_init_infections.csv"))
#df_agents_exp_raw <- read.csv(here("data_output/run_seedtest6/df_agents_seedtest6.csv"))
```


```{r}
# exclude agent 0
df_agents_exp_raw$patient0 <- as.logical(df_agents_exp_raw$patient0)
df_agents_exp_raw  <- df_agents_exp_raw[!df_agents_exp_raw$patient0,]

# load and merge homeoffice-data
df_homeoffice <- read.csv(here("data_input/homeoffice/Alipouretal_WFH_Germany-master/Alipouretal_WFH_Germany-master/wfh_nace2.csv"))
df_agents_exp_raw <- merge(df_agents_exp_raw, df_homeoffice, by.x="nace2_division", by.y="nace2")

prepped_df_list_exp <- prep_data(df_agents_exp_raw, aggregate_agents=TRUE)
df <- prepped_df_list_exp$df

df$age_group_rki <- as.factor(df$age_group_rki)
```

```{r}
counter <- 1
dfs <- c()
for (mmi in unique(df$master_model_index)){
  df_temp <- df[df$master_model_index == mmi,]
  
  m <- glm.nb(
    formula=len_post_infection_chain
    ~ 
    + household_size
    + age_group_rki
    , 
    data=df_temp)
  
  
  df_b <- data.frame(
    model=counter,
    b_intercept=m$coefficients[["(Intercept)"]],
    b_household_size=m$coefficients[["household_size"]],
    b_age_5=m$coefficients[["age_group_rki5"]],
    b_age_15=m$coefficients[["age_group_rki15"]],
    b_age_35=m$coefficients[["age_group_rki35"]],
    b_age_60=m$coefficients[["age_group_rki60"]],
    b_age_80=m$coefficients[["age_group_rki80"]]
    )
  dfs[[counter]] <- df_b
  counter <- counter + 1

}
```

```{r}
df_agg <- do.call(rbind, dfs)

df_mean_b_intercept <- get_replications(df_agg, mean, "b_intercept")
df_mean_b_household_size <- get_replications(df_agg, mean, "b_household_size")
df_mean_b_age_5 <- get_replications(df_agg, mean, "b_age_5")
df_mean_b_age_15 <- get_replications(df_agg, mean, "b_age_15")
df_mean_b_age_35 <- get_replications(df_agg, mean, "b_age_35")
df_mean_b_age_60 <- get_replications(df_agg, mean, "b_age_60")
df_mean_b_age_80 <- get_replications(df_agg, mean, "b_age_80")
```

```{r}
(
  ggplot()
  + geom_point(data=df_mean_b_age_5, mapping=aes(x=n, y=estimate, color="age group 5"))
  + geom_line(data=df_mean_b_age_5, mapping=aes(x=n, y=estimate, color="age group 5"))
  
  + geom_point(data=df_mean_b_age_15, mapping=aes(x=n, y=estimate, color="age group 15"))
  + geom_line(data=df_mean_b_age_15, mapping=aes(x=n, y=estimate, color="age group 15"))
  
  + geom_point(data=df_mean_b_age_35, mapping=aes(x=n, y=estimate, color="age group 35"))
  + geom_line(data=df_mean_b_age_35, mapping=aes(x=n, y=estimate, color="age group 35"))
  
  + geom_point(data=df_mean_b_age_60, mapping=aes(x=n, y=estimate, color="age group 60"))
  + geom_line(data=df_mean_b_age_60, mapping=aes(x=n, y=estimate, color="age group 60"))
  
  + geom_point(data=df_mean_b_age_80, mapping=aes(x=n, y=estimate, color="age group 80"))
  + geom_line(data=df_mean_b_age_80, mapping=aes(x=n, y=estimate, color="age group 80"))
  
  + xlab("Number of replications")
  + ylab("Average number of infected agents")
)
```

```{r}
(
  ggplot()
  + geom_point(data=df_mean_b_household_size, mapping=aes(x=n, y=estimate, color="Household size"))
  + geom_line(data=df_mean_b_household_size, mapping=aes(x=n, y=estimate, color="Household size"))
  + xlab("Number of replications")
  + ylab("Average number of infected agents")
  + ylim(0, NaN)
)
```

```{r}
(
  ggplot()
  + geom_point(data=df_mean_b_intercept, mapping=aes(x=n, y=estimate, color="Intercept"))
  + geom_line(data=df_mean_b_intercept, mapping=aes(x=n, y=estimate, color="Intercept"))
  + xlab("Number of replications")
  + ylab("Average number of infected agents")
  + ylim(NaN, 0)
)
```




### Eval reps of experimental model

```{r}
df_ori <- read.csv(here("data_output/run_big_run_weekend_50/df_agents_big_run_weekend_50.csv"))
```

```{r}
df <- df_ori

df$Prioritization <- factor(
  x=df$contact_tracing_population_sort_mode,
  levels=c("random", "super-spreaders", "young", "old", "household_size", "inc_rank_emp", "inc_rank_sim", "age"),
  labels=c("Random", "Age+HH", "Young", "Old", "HH", "Inc. emp.", "Inc. sim.", "Age")
)
  
  
df$ever_infected <- ifelse(df$ever_infected=="True", 1, 0)
#df$ever_infected_with_symptoms <- ifelse(df$ever_infected_with_symptoms=="True", 1, 0)
```

```{r}
# counts per replication 
df_agg <- aggregate(
   x=list(
     "ever_infected"=df$ever_infected
     #"ever_infected_with_symptoms"=df$ever_infected_with_symptoms
     ),
   by=list(
     #"replication"=df$replication,
     "Prioritization"=df$Prioritization, 
     "contact_tracing_frac"=df$contact_tracing_frac,
     "master_model_index"=df$master_model_index
     ),
   FUN=sum
 )
```

```{r}
counter <- 1
dfs <- c()
for (prio in unique(df_agg$Prioritization)){
  for (ctf in unique(df_agg$contact_tracing_frac)){
    df_temp <- get_replications(df_agg[df_agg$Prioritization == prio & df_agg$contact_tracing_frac == ctf,], mean, "ever_infected")
    df_temp$Prioritization <- prio
    df_temp$contact_tracing_frac <- ctf
    dfs[[counter]] <- df_temp
    counter <- counter + 1
  }
}
```

```{r}
df_mean <- do.call(rbind, dfs)
```

```{r}

for (ctf in unique(df_mean$contact_tracing_frac)){
  
  (
  g <- ggplot(data=df_mean[df_mean$contact_tracing_frac == ctf,], mapping=aes(x=n, y=estimate, color=Prioritization))
  + geom_point()
  + geom_line()
  + ylim(0, NaN)
  + xlab("Number of models (with 50 replications)")
  + ylab("Average number of infected agents")
  )
  print(g)
}
```